name: pipeline-basico
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executa comando
        run: echo "Configuração inicial do pipeline"
      - run: node --version
